### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Huster-Hq** [haoshao-nku/medical_seg#19]
Hello, I changed to another polyp dataset, and the following bugs appear. I don't know why this happens. The GT masks are the same size for each image.

`/data/huqiang/code/Segmentation/Image/Fully-supervised/medical_seg/mmsegmentation/mmseg/datasets/transforms/formatting.py:81: UserWarning: Please pay attention your ground truth segmentation map, usually the segmentation map is 2D, but got (224, 224, 3)
  warnings.warn('Please pay attention your ground truth '
Traceback (most recent call last):
  File "tools/train.py", line 104, in <module>
    main()
  File "tools/train.py", line 100, in main
    runner.train()
  File "/data/huqiang/anaconda3/envs/medical_seg/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/data/huqiang/anaconda3/envs/medical_seg/lib/python3.8/site-packages/mmengine/runner/loops.py", line 289, in run
    self.run_iter(data_batch)
  File "/data/huqiang/anaconda3/envs/medical_seg/lib/python3.8/site-packages/mmengine/runner/loops.py", line 313, in run_iter
    outputs = self.runner.model.train_step(
  File "/data/huqiang/anaconda3/envs/medical_seg/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/data/huqiang/anaconda3/envs/medical_seg/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
  File "/data/huqiang/anaconda3/envs/medical_seg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/huqiang/anaconda3/envs/medical_seg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/huqiang/code/Segmentation/Image/Fully-supervised/medical_seg/mmsegmentation/mmseg/models/segmentors/base.py", line 94, in forward
    return self.loss(inputs, data_samples)
  File "/data/huqiang/code/Segmentation/Image/Fully-supervised/medical_seg/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 178, in loss
    loss_decode = self._decode_head_forward_train(x, data_samples)
  File "/data/huqiang/code/Segmentation/Image/Fully-supervised/medical_seg/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 139, in _decode_head_forward_train
    loss_decode = self.decode_head.loss(inputs, data_samples,
  File "/data/huqiang/code/Segmentation/Image/Fully-supervised/medical_seg/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 262, in loss
    losses = self.loss_by_feat(seg_logits, batch_data_samples)
  File "/data/huqiang/code/Segmentation/Image/Fully-supervised/medical_seg/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 305, in loss_by_feat
    seg_label = self._stack_batch_gt(batch_data_samples)
  File "/data/huqiang/code/Segmentation/Image/Fully-supervised/medical_seg/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 289, in _stack_batch_gt
    return torch.stack(gt_semantic_segs, dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [1, 224, 224] at entry 0 and [224, 224, 3] at entry 2`

**Comment by pangda882** [comment]
加1，你解决了？
do you slove？
can you tell me the solution，thanks！
